# Generated by Django 4.2.6 on 2023-10-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_dataanalysis_added_alter_dataanalysis_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataanalysis',
            name='end_year',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='impact',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='start_year',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
