# Generated by Django 4.2.6 on 2023-10-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_dataanalysis_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataanalysis',
            name='added',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='end_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='impact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='insight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='intensity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='likelihood',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='pestle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='published',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='relevance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='sector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='start_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='topic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
